config/routes.rb
Rails.application.routes.draw do
  resources :to_dos

end

app/models/to_do.rb
class ToDo < ActiveRecord::Base
  validates :sumary, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  def index
    @to_dos = ToDo.all
  end
  def new
    @to_do= ToDo.new
  end
  def create
    @to_do= ToDo.new(to_do_params)
    if @to_do.save
      redirect_to to_dos_path
    else
      render :new
    end
  end
  def show
    @to_do=ToDo.find(params[:id])
  end
  def destroy
    @to_do=ToDo.destroy(params[:id])
    redirect_to to_dos_path
  end



  private

  def to_do_params
    params.require(:to_do).permit( :sumary, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/to_do_helper.rb
module ToDoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag :application %>
  <%= csrf_meta_tags %>
  </head>
<body>

<%= yield %>

</body>
</html>

app/views/to_dos/index.html.erb
<h1>LISTA_ToDo</h1>
<p><b>Lista rzeczy do zrobienia: </b></p>

<%@to_dos.each do |to_do|%>
  <div>
    <h3>
      <%=link_to(to_do.sumary, to_do_path(to_do)) %>
    </h3>
    <p><%=to_do.description%></p>
    <hr></hr>
  </div>
<%end%>
<%=link_to("dodaj zadanie", new_to_do_path)%>
<%=image_tag("slonce") %>

app/views/to_dos/new.html.erb
<h1>Dodaj zadanie</h1>

<% @to_do.errors.full_messages.each do |error| %>
  <p class="errors"><%= error %></p>
<% end %>
<%= form_for(@to_do) do |f| %>
  <div>
    <%= f.label :sumary %>
    <%= f.text_field :sumary, {:maxlength => 15} %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description,  {:maxlength => 50} %>
  </div>
  <%= f.submit "save" %>
<% end %>

app/views/to_dos/show.html.erb
<h1> zadanie: <%= @to_do.sumary %> </h1>
<p> <%= @to_do.description %> </p>
<%= button_to "usun", @to_do, method: :delete%>
<%= link_to "wszystkie zadania" , to_dos_path %>